hbz/lobid-gnd

conf/context.jsonld
Resolves #89.
Furthermore, I added `skos:narrowMatch` to the context. I noticed that it currently is used in 249 entries with `skos:narrowMatch`, see http://lobid.org/gnd/search?q=_exists_%3A%22skos%3AnarrowMatch%22. (As I removed the skos prefix in c1ed3434a446109d55eade36f4911ea1c3662245 the whole URI would have been used after re-indexing.) 
We will have to re-index the whole GND to see the changes. Do we need an issue for this? If yes, we could adjust #146...
=> Add properties for provenance information to context

checkCompactedProperties.sh, cron.sh
See #171.
If deployed the gnd updates will be checked automatically. If uncompacted fields are found a mail is wrotten to the lobid admins. This also prevents updating the data, so you should take some action so that the data will not be outdated.
If indexing a fulldump, the script `checkCompactedProperties.sh` must be called manually. It will check the newest "gnd"-prefixed index.
=> 171 check not compacted fields

app/apps/Convert.java, test/apps/ConvertTest.java
Always sort resulting data for consistency (original, new, merged)
Will resolve https://github.com/hbz/lobid-gnd/issues/198
=> Remove duplicate sameAs entries when merging GND and EntityFacts

app/controllers/HomeController.java, app/controllers/Reconcile.java, app/modules/IndexComponent.java, test/modules/IndexQueryTest.java
- Limit main query to name fields
- Boost optional properties query
Will resolve https://github.com/hbz/lobid-gnd/issues/228
=> Tweak reconciliation query

app/models/GndOntology.java, test/controllers/ReconcileTest.java, test/models/GndOntologyTypeTests.java
Include property types only where values are GND entities
Will resolve https://github.com/hbz/lobid-gnd/issues/241
=> Fix data extension response metadata

app/controllers/Reconcile.java
Like `/gnd/reconcile?queries={"q1":{"query":"Twain, Mark"}}`
Deployed to test, see:
https://test.lobid.org/gnd/reconcile
https://test.lobid.org/gnd/reconcile?queries={"q1":{"query":"Twain,+Mark"}}
=> Fix reconcile GET queries in the browser

app/controllers/Reconcile.java, test/controllers/ReconcileTest.java
While working on https://codeberg.org/fsteeg/recon-artikel I discovered we're not using `identifierSpace` correctly in our reconciliation service manifest.
Quoting from [the spec](https://reconciliation-api.github.io/specs/latest/#identifier-and-schema-spaces):
> If two different reconciliation services expose the same entities and properties, then they SHOULD use the same identifier and schema space URIs, signalling that (for instance) the Data Extension service of the first one can be used on reconciliation candidates by the second
See also discussion on the [mailing list]( https://lists.w3.org/Archives/Public/public-reconciliation/2019Oct/0002.html):
> identifierSpace: This property defines the base URL under which results returned by the reconciliation service are located.  For …
=> Fix identifierSpace in reconciliation service manifest

app/controllers/Reconcile.java, app/models/AuthorityResource.java, test/controllers/ReconcileTest.java
This implements the suggested spec change from https://github.com/reconciliation-api/specs/pull/73
To be used by a client e.g. as in https://github.com/reconciliation-api/testbench/pull/28
(And two minor fixes I encountered while working on that.)
Deployed to test, see new `broader` types e.g. in:
`curl https://test.lobid.org/gnd/reconcile/` (`defaultTypes`)
`curl https://test.lobid.org/gnd/reconcile/suggest/type?prefix=werk`
=> Add single-level broader IDs for default and suggested types

app/apps/ConvertBaseline.java
Triggered by mail from L.Z. on 2022-08-23.
Attempted reindexing updates since 2022-06-13, aborted due to XML processing error on updates for 2022-07-14. With this change, the entry causing the error ([dnb/1262530970](https://d-nb.info/gnd/1262530970/about/lds.rdf)) was skipped, and processing continued.
Opening #321 for the actual processing error and missing entry ([lobid/1262530970](https://lobid.org/gnd/1262530970)).
=> Catch exceptions to avoid aborting when processing OAI-PMH XML

app/apps/Index.java
Resulted in missing shards on ES cluster when indexing updates.
Will resolve #347.
=> Don't set `number_of_replicas` when indexing GND data

app/apps/ConvertUpdates.java
=> Change daily updates to hourly updates

app/controllers/HomeController.java, app/models/AuthorityResource.java, app/views/advanced.scala.html, app/views/main.scala.html, app/views/search.scala.html, app/views/search_advanced.scala.html, conf/index-settings.json, conf/routes, public/stylesheets/main.css
See https://jira.hbz-nrw.de/browse/RPB-38
=> Add RPPD advanced search (RPB-38)

app/controllers/HomeController.java, app/models/AuthorityResource.java, app/views/index.scala.html, public/stylesheets/main.css, transformAndIndexRppd.sh
See https://jira.hbz-nrw.de/browse/RPB-46
=> Show current anniversaries on index page (RPB-46)

app/apps/Convert.java
Before this, when new fields were added in the GND source data, they would result in non-compacted URI field names, since they are not in the context. This is checked by `checkCompactedProperties.sh` for the test index, and production indexing is blocked if there are uncompacted fields. With this change, we remove the statements that would result in such fields instead and log that as an error.
=> Remove statements that would result in uncompacted index fields

cron.sh
This redundancy in updating the data should bring more stability in being in sync with upstream data.
See #372.
=> Update every day a whole day as fallback

app/apps/ConvertUpdates.java
See [#372.](https://github.com/hbz/lobid-gnd/issues/372#issuecomment-1953762430).
=> Change CET time to UTC

app/controllers/HomeController.java, app/models/AuthorityResource.java, app/views/error.scala.html, app/views/search.scala.html
See https://jira.hbz-nrw.de/browse/RPB-153.
Problem in prod:
- Result list: https://rppd.lobid.org/search?q=NOT+_exists_%3AgndIdentifier
- JSON links e.g. https://rppd.lobid.org/ddf9bc44-a80b-41fe-996d-5a38c041c482
Deployed to test:
- Result list: http://test.rppd.lobid.org/search?q=NOT+_exists_%3AgndIdentifier
- JSON links e.g. http://test.rppd.lobid.org/6277a7fa-4852-49de-91b8-f465491a9f24
(Also fixed wrong person number in footer of search result error page.)
=> Handle missing `gndIdentifier` in search result and JSON link

app/models/AuthorityResource.java
See https://jira.hbz-nrw.de/browse/RPB-157
Deployed to test:
http://test.rppd.lobid.org/1051174910
http://test.rppd.lobid.org/1229724990
=> Fix handling of non-ISO dates for display in UI (RPB-157)

app/models/GndOntology.java, test/models/GndOntologyLabelTests.java
Will resolve #256.
Deployed to test for a single entry (via update for its `dateModified`): http://test.lobid.org/gnd/1085901955
After production deployment updates will start getting the correct label, old entries with next baseline.
=> Use only direct children, not nested (e.g. `broader`) labels (#256)

app/models/GndOntology.java, conf/description-level.rdf, test/models/GndOntologyLabelTests.java
Will resolve #359.
Applies to new transformations. Deployed to test, re-ran updates for 2024-06-05:
https://test.lobid.org/gnd/search?q=describedBy.dateModified:2024-06-05&format=json
=> Add `description-level` vocab, add full IDs for lookups (#359)

app/controllers/HomeController.java, app/models/AuthorityResource.java, app/views/api.scala.html, test/controllers/SuggestionsTest.java
E.g. [preferredName,*_dateOfBirth in_placeOfBirth,†_dateOfDeath in_placeOfDeath](http://test.rppd.lobid.org/search?q=Brentano&format=json%3ApreferredName%2C*_dateOfBirth+in_placeOfBirth%2C%E2%80%A0_dateOfDeath+in_placeOfDeath)
See https://jira.hbz-nrw.de/browse/RPB-169
=> RPPD: Support `label_fieldName` auto-complete templates, e.g. `*_dateOfBirth` (RPB-169)

app/controllers/HomeController.java, app/models/AuthorityResource.java, app/views/api.scala.html, test/controllers/SuggestionsTest.java
E.g. [preferredName,*_dateOfBirth in_placeOfBirth,†_dateOfDeath in_placeOfDeath](https://test.lobid.org/gnd/search?q=Twain&format=json%3ApreferredName%2C*_dateOfBirth+in_placeOfBirth%2C%E2%80%A0_dateOfDeath+in_placeOfDeath)
New sample at https://test.lobid.org/gnd/api#auto-complete
See https://jira.hbz-nrw.de/browse/RPB-169
=> Support `label_fieldName` auto-complete templates, e.g. `*_dateOfBirth` (RPB-169)

app/controllers/HomeController.java, app/modules/IndexComponent.java, build.sbt, conf/routes
See https://jira.hbz-nrw.de/browse/RPB-43
=> Serve robots.txt based on `doNotCrawl` in Strapi export (RPB-43)

app/controllers/HomeController.java, app/controllers/Reconcile.java, app/views/gnd.scala.html, app/views/preview.scala.html, app/views/reconcile.scala.html, conf/application.conf, conf/routes, test/controllers/ReconcileIntegrationTest.java
Basic idea: we replace the internal `@routes.Reconcile.reconcile()` route (`/gnd/reconcile/`) with the host name from `conf/application.conf` (set to `https://reconcile.lobid.org` for testing). The web server proxies `/` to `/gnd/reconcile/` (as well as `/gnd/` -> `/gnd/` for assets and view / preview links).
=> Set up reconciliation service for subdomain usage

app/models/GndOntology.java, test/models/GndOntologyLabelTests.java
=> add missing terms

app/controllers/Reconcile.java, test/controllers/ReconcileUnitTest.java
These are the reserved characters: 
`+ - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ /` 
according to https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-query-string-query.html#_reserved_characters
We need to remove all of them from the query string.
Resolves #434
=> 434 fix query cleaning
