hbz/lobid-gnd

app/controllers/HomeController.java
conf/routes

Will resolve https://github.com/hbz/lobid-gnd/issues/35
See http://stage.lobid.org/gnd/

Handle trailing slashes

---

app/modules/IndexComponent.java
test/modules/IndexTest.java
test/ttl/118512676.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/33

Use unicode normalization form C (NFC) for index data

---

README.textile
app/modules/IndexComponent.java
test/modules/IndexTest.java
test/ttl/1081942517.ttl
test/ttl/118624822.ttl
test/ttl/141568992.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/40

Tweak query boosting

---

app/controllers/HomeController.java
app/views/search.scala.html
conf/application.conf
test/apps/ConvertTest.java
test/ttl/118649019.ttl
test/ttl/7855044-0.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/25

 Don't show `Gods` and `Spirits` as top level types in facet

---

app/models/AuthorityResource.java
app/views/details.scala.html
test/ttl/1153578379.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/47

Show only first 3 items for JOINED table entries, and link to JSON

---

app/models/AuthorityResource.java

Will resolve https://github.com/hbz/lobid-gnd/issues/76

Add `broaderTermGeneric` to details view

---

app/controllers/HomeController.java
app/models/AuthorityResource.java
app/models/GndOntology.java

Will resolve https://github.com/hbz/lobid-gnd/issues/68

Show works in GND as a field in their creator's details view 

---

app/apps/Convert.java
app/models/AuthorityResource.java
app/views/search.scala.html
test/apps/ConvertTest.java
test/modules/IndexTest.java

See https://github.com/hbz/lobid-gnd/issues/81

Remove array from `gndIdentifier`

---

.travis.yml
app/apps/Convert.java
app/controllers/HomeController.java
app/models/EntityFacts.java
app/modules/AuthoritiesModule.java
app/modules/IndexComponent.java
build.sbt
conf/application.conf
test/apps/ConvertTest.java
test/modules/IndexTest.java

Will resolve https://github.com/hbz/lobid-gnd/issues/67

Switch from embedded index to Elasticsearch server 

---

app/models/AuthorityResource.java
conf/context.jsonld

Resolves #101. I am not sure whether there is a need to update the tests. Running tests locally made every test fail and I don't have the time today to fix this. We'll see what travis says.

Add type to asWKT in JSON-LD context

---

app/apps/Convert.java
app/apps/ConvertUpdates.java
app/controllers/HomeController.java
app/modules/IndexComponent.java
app/views/api.scala.html
app/views/main.scala.html
conf/application.conf
conf/index-settings.json
public/stylesheets/main.css
test/controllers/AcceptIntegrationTest.java
test/controllers/AcceptUnitTest.java
test/controllers/SuggestionsTest.java
test/modules/IndexQueryTest.java
test/modules/IndexTest.java

Add autocomplete support

---

app/apps/Convert.java
app/apps/ConvertBaseline.java
app/apps/ConvertUpdates.java
conf/application.conf

Will resolve https://github.com/hbz/lobid-gnd/issues/111

Separate getting RDF-XML OAI-PMH updates from JSON-LD conversion

---

app/apps/Convert.java
app/apps/ConvertBaseline.java
app/controllers/HomeController.java
app/modules/IndexComponent.java
conf/application.conf
test/apps/ConvertTest.java
test/controllers/HomeControllerTest.java
test/models/ModelTest.java
test/models/RdfConverterTests.java
test/modules/IndexQueryTest.java
test/modules/IndexTest.java
test/ttl/1090750048.ttl
test/ttl/111508401.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/117

Redirect with 301 if newer resource exists

---

app/controllers/Accept.java
app/controllers/HomeController.java
app/models/RdfConverter.java
app/views/api.scala.html
test/controllers/AcceptIntegrationTest.java
test/controllers/AcceptUnitTest.java
test/controllers/HomeControllerTest.java

Will resolve https://github.com/hbz/lobid-gnd/issues/91

Support bulk requests

---

app/views/main.scala.html

See: https://github.com/hbz/lobid-gnd/issues/133, https://github.com/lobid/lobid.github.com/pull/30
Deployed to test: http://test.lobid.org/gnd

Tweak nav bar for documentation

---

app/controllers/Accept.java
test/controllers/AcceptIntegrationTest.java

Will resolve https://github.com/hbz/lobid-gnd/issues/137

Fix JSON default for "Accept: */*" header

---

app/views/main.scala.html

Will resolve https://github.com/hbz/lobid-gnd/issues/114

Only autofocus on search field if `q` is empty

---

app/modules/IndexComponent.java
conf/GND-deprecated.sh
test/modules/IndexTest.java

Resolves https://github.com/hbz/lobid-gnd/issues/151

 Add script to create full list of deprecated URIs for deletion

---

app/controllers/HomeController.java
app/modules/IndexComponent.java
app/views/error.scala.html
test/controllers/AcceptIntegrationTest.java
test/controllers/HomeControllerTest.java
test/modules/IndexQueryTest.java

Will resolve https://github.com/hbz/lobid-gnd/issues/156

Handle errors on invalid queries

---

app/apps/Convert.java
app/apps/ConvertBaseline.java
app/apps/ConvertUpdates.java
app/controllers/Accept.java
app/controllers/HomeController.java
app/controllers/Reconcile.java
app/models/AuthorityResource.java
app/models/GndOntology.java
app/models/LinkWithImage.java
app/models/RdfConverter.java
app/modules/AuthoritiesModule.java
app/modules/IndexComponent.java
app/views/api.scala.html
app/views/dataset.scala.html
app/views/details.scala.html
app/views/error.scala.html
app/views/index.scala.html
app/views/main.scala.html
app/views/preview.scala.html
app/views/search.scala.html

See https://github.com/hbz/lobid/issues/338

Consistent license information

---

app/models/GndOntology.java
conf/agrelon.rdf
conf/gnd.rdf
test/models/GndOntologyLabelTests.java

Will resolve https://github.com/hbz/lobid-gnd/issues/165

Update Agrelon and GNDO for labels, types, and properties

---

conf/context.jsonld

Fixes https://github.com/hbz/lobid-gnd/issues/163

Remove prefixes from context, add missing property

---

conf/context.jsonld

See https://github.com/hbz/lobid-gnd/issues/146#issuecomment-448154559

Fix relatedSubjectHeading typo

---

app/controllers/HomeController.java
app/controllers/Reconcile.java
app/models/AuthorityResource.java
app/modules/IndexComponent.java
app/views/search.scala.html
conf/index-settings.json
conf/routes
test/controllers/HomeControllerTest.java
test/modules/IndexQueryTest.java

Will resolve https://github.com/hbz/lobid-gnd/issues/164

Support sorting of results

---

app/controllers/Reconcile.java
test/controllers/ReconcileTest.java
test/ttl/16269284-5.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/188

Remove reserved chars in reconciliation query

---

app/apps/Convert.java
conf/context.jsonld

Resolves https://github.com/hbz/lobid-gnd/issues/185

Use schema:sameAs instead of owl:sameAs

---

app/apps/Convert.java
app/controllers/HomeController.java
app/views/index.scala.html
conf/application.conf
conf/logback.xml
test/apps/ConvertTest.java
test/modules/IndexQueryTest.java
test/ttl/1173843892.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/187

Merge, don't replace sameAs data 

---

app/controllers/Reconcile.java

Replace `Person` with `DifferentiatedPerson`
See https://github.com/hbz/lobid-gnd/issues/193

Tweak default types for reconciliation

---

app/models/AuthorityResource.java
conf/context.jsonld
test/models/ModelTest.java
test/ttl/4057120-8.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/192

Handle polygon locations

---

app/models/AuthorityResource.java

Will resolve https://github.com/hbz/lobid-gnd/issues/200

Don't link to .html in GND links

---

app/controllers/Reconcile.java
app/views/api.scala.html
conf/routes
test/controllers/ReconcileTest.java

Will resolve https://github.com/hbz/lobid-gnd/issues/175

Support GET for reconciliation requests

---

app/controllers/HomeController.java
app/controllers/Reconcile.java
app/models/GndOntology.java
conf/routes

Will resolve https://github.com/hbz/lobid-gnd/issues/206

Support OpenRefine Suggest API

---

app/controllers/HomeController.java
app/controllers/Reconcile.java
app/modules/IndexComponent.java
test/controllers/ReconcileTest.java
test/modules/IndexQueryTest.java

Append `.id` or `.label` to the selected property
Will resolve https://github.com/hbz/lobid-gnd/issues/224

Fix reconciliation query properties search

---

README.textile
app/apps/Convert.java
app/apps/ConvertBaseline.java
app/apps/Index.java
app/controllers/HomeController.java
app/controllers/Reconcile.java
app/models/GndOntology.java
app/modules/IndexComponent.java
conf/application.conf
test/apps/ConvertTest.java
test/modules/IndexTest.java

See https://lists.w3.org/Archives/Public/public-reconciliation/2019Oct/0002.html

Update identifierSpace and schemaSpace

---

README.textile
app/apps/Convert.java
app/apps/ConvertBaseline.java
app/apps/Index.java
app/controllers/HomeController.java
app/controllers/Reconcile.java
app/models/GndOntology.java
app/modules/IndexComponent.java
conf/application.conf
test/apps/ConvertTest.java
test/modules/IndexTest.java

Config hosts and cluster, not just index names
Will resolve https://github.com/hbz/lobid-gnd/issues/238

Set up separate index configs for boot and prod

---

app/apps/ConvertUpdates.java
app/helper/Email.java
build.sbt
conf/application.conf

See #260.
Other than usually, to be notified about a possible failing update this branch is already active on production.

Retry to get update and send an email if this fails

---

app/models/AuthorityResource.java
app/views/details.scala.html
app/views/index.scala.html

- use a script at lobid to proxy images
- use lobid as proxy for the tileserver
See hbz/lobid#421.

Proxy external links

---

app/views/details.scala.html

Resolves https://github.com/hbz/lobid-gnd/issues/265

Fix EntityFacts link

---

app/controllers/HomeController.java
conf/index-settings.json
test/modules/IndexQueryTest.java
test/ttl/16330586-9.ttl

Will resolve https://github.com/hbz/lobid-gnd/issues/263

Add variantName.ascii sub-field with asciifolding filter

---

app/views/details.scala.html

Use short and more permanent links for LDS and EntitFacts so that we do not have to update them any time soon. See https://github.com/hbz/lobid-gnd/pull/266#issuecomment-691093021

Use more permanent short links for EntityFacts & LDS

---

app/models/AuthorityResource.java
app/views/details.scala.html
app/views/index.scala.html
app/views/main.scala.html
app/views/search.scala.html

See https://github.com/hbz/lobid/issues/423

Improve accessibility for lobid-gnd

---

app/controllers/HomeController.java
app/controllers/Reconcile.java

See https://github.com/hbz/lobid-gnd/issues/272

Pretty print reconciliation responses

---

app/views/details.scala.html

- set maxZoom to 17
See https://github.com/hbz/lobid/issues/309.
Test e.g. https://test.lobid.org/gnd/4031483-2

Switch to use hbz' tileserver

---

README.textile
app/apps/Convert.java
baseline.sh
conf/application.conf

See https://github.com/hbz/lobid-gnd/issues/255
I wrote the script while manually running the individual steps. I suggest we do a full test of the script on the next new baseline. To fill the gap of updates since the creation date of the baseline file, I added the manual steps in comments. Perhaps we can then automate these too. I don't see a straightforward way right now. What I mentioned in the standup today does not actually work since we always need to know the creation date of the baseline file to know which updates we need.

Update README and config, add work in progress script

---

app/views/main.scala.html

This is where the lobid-admin address definitely is the best fit.

Use lobid-admin email address for feedback link

---

app/controllers/Reconcile.java
test/controllers/ReconcileIntegrationTest.java
test/controllers/ReconcileUnitTest.java

Don't replace special characters in ranges or AND/OR groups

---

app/apps/ConvertUpdates.java

Only write last successful update date after actual success

---

app/controllers/Reconcile.java
app/modules/IndexComponent.java
test/controllers/ReconcileIntegrationTest.java
test/controllers/ReconcileUnitTest.java

Only clean reconciliation queries if they are invalid (#309)

---

README.textile
app/apps/ConvertUpdates.java
test/apps/ConvertUpdatesTest.java
test/apps/DataWorkflowTests.java

Improve fetching updates

---

checkCompactedProperties.sh
conf/context.jsonld
test/models/RdfConverterTests.java
test/ttl/300126603.ttl
test/ttl/300941315.ttl

Add new properties to context (#326)

---

baseline.sh
conf/context.jsonld
test/models/RdfConverterTests.java
test/ttl/4191581-1.ttl

s. [http://lobid.org/gnd/search?q=http\\:\\/\\/www:*](http://lobid.org/gnd/search?q=http%5C%3A%5C%2F%5C%2Fwww%3A*)

Add skos:closeMatch to context

---

app/apps/ConvertUpdates.java
baseline.sh
cron.sh

Some improvements in scripts and other tweaks while working on issues that required unexpected reindexing and updating. See individual commits for details. Is currently deployed on quaoar1 and 2.

Improvements in scripts and other tweaks

---

app/apps/Convert.java
app/apps/ConvertBaseline.java
app/apps/ConvertUpdates.java
app/apps/Index.java
app/controllers/HomeController.java
app/views/details.scala.html
build.sbt

Will resolve #336 and resolve #321.
Deployed for testing on quaoar2: `sol@quaoar2:~/git/lobid-gnd$`, e.g.
`sbt "runMain apps.ConvertUpdates 2022-10-16 2022-10-16"`
`sbt -Dindex.prod.name=gnd-test "runMain apps.Index updates"`
404 page e.g. at https://test.lobid.org/gnd/123

Fix issues in XML processing, serve 404 HTML page

---

app/controllers/Reconcile.java
test/controllers/ReconcileIntegrationTest.java

Use query object from index to hook into full preprocessing

---

app/views/api.scala.html
app/views/index.scala.html
conf/GND-deprecated.sh
conf/application.conf

Small PR to secure lobid links.

Use https for hardcoded lobid links

---

conf/context.jsonld

Add `gndo:usingInstructions`

---

app/apps/Convert.java
conf/context.jsonld
conf/gnd.rdf
test/apps/ConvertTest.java
test/models/GndOntologyPropertiesTests.java
test/modules/IndexQueryTest.java
test/ttl/1308401809.ttl
test/ttl/4477598-2.ttl

Should finally resolve (partially) #333 . Might resolve (partially) https://github.com/hbz/lobid/issues/419 .

Fix `@context` for `usingInstructions`& `professionOrOccupation`

---

conf/dataset.jsonld

Deployed to http://stage.lobid.org/gnd/dataset.
Functional and code review @acka47 .
Resolves #368.

Update frequency in dataset description (#368)

---

cron.sh

Will make it harder to misconfigure like I did resulting in https://github.com/hbz/lobid-gnd/issues/362#issuecomment-1954185720.

Use variables for index names

---

transformAndIndexRppd.sh

See https://jira.hbz-nrw.de/browse/RPB-109

Create new index and update alias in RPPD script (RPB-109)

---

app/views/api.scala.html
app/views/reconcile.scala.html

Will resolve #381
Will resolve #382
Deployed to test:
http://test.lobid.org/gnd/reconcile
http://test.lobid.org/gnd/api

Move reconciliation API documentation and update `/reconcile` page

---

app/controllers/HomeController.java
app/models/AuthorityResource.java
app/views/details.scala.html

See https://jira.hbz-nrw.de/browse/RPB-154

Fix links and missing labels in RPPD UI

---

app/models/AuthorityResource.java
app/views/search.scala.html

Use en dash for date ranges

---

transformAndIndexRppd.sh

To avoid problems like https://jira.hbz-nrw.de/browse/RPB-189

Only switch RPPD index if count is larger than 10000

---

.github/workflows/build.yml
app/models/AuthorityResource.java

See https://jira.hbz-nrw.de/browse/RPB-259

Support additional info in URL fields, display after link (RPB-259)

---

baseline.sh

Updates after running script and following instructions in comments for #414.
Assigning @Phu2 for review due to related issue #419.

Update baseline.sh comments for current updates usage

---

app/apps/Convert.java
conf/context.jsonld

Add missing properties to JSON-LD context

---

app/controllers/HomeController.java
test/controllers/SuggestionsTest.java
test/ttl/1257107356.ttl

Escape HTML in autocomplete suggestion labels (#428)
